version: '3.8'
services:
  testdb:
    container_name: testlientrydb
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testlientrydb
    networks:
      - api-test
networks:
  api-test:
