version: '3.8'
services:
  db:
    container_name: lientrydb
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lientrydb
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - api-dev
networks:
  api-dev:
volumes:
  dbdata:
